apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsiplugin-pv
  labels:
    name: data-iscsiplugin
spec:
  storageClassName: static-iscsi
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ISCSI
    volumeHandle: iscsi-data-id
    volumeAttributes: 
      # iSCSI target addr:port
      targetPortal: "172.31.0.100:3260"
      portals: "[]"
      iqn: "iqn.2005-10.org.freenas.ctl:k8s"
      lun: "0"
      iscsiInterface: "default"
      discoveryCHAPAuth: "false"
      sessionCHAPAuth: "false"
